In [1]:
import tensorflow as tf
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

DATASETDIR = "E:\src\dataset\kagglecatsanddogs_3367a\PetImages"
CATEGORIES = ["Dog", "Cat"]



In [2]:
IMG_SIZE = 50
training_data = []
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATASETDIR, category)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                training_data.append([new_array, class_num])
            except Exception as e:
                pass
create_training_data()

In [14]:
print(len(training_data))

24946


In [15]:
import random

random.shuffle(training_data)

In [16]:
for sample in training_data[:10]:
    print(sample[1])

0
0
1
1
1
0
0
0
1
1


In [17]:
X = []
y = []


In [18]:
IMG_SIZE = 50
for features, label in training_data:
    X.append(features)
    y.append(label)
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

In [23]:
import pickle

pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [24]:
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)

In [25]:
print(X[0])

[[[ 40]
  [ 43]
  [ 37]
  ..., 
  [ 95]
  [ 42]
  [ 36]]

 [[ 65]
  [ 90]
  [ 65]
  ..., 
  [ 52]
  [ 46]
  [ 42]]

 [[101]
  [101]
  [ 64]
  ..., 
  [ 50]
  [ 44]
  [ 52]]

 ..., 
 [[ 71]
  [ 33]
  [ 45]
  ..., 
  [142]
  [121]
  [131]]

 [[ 61]
  [ 50]
  [ 57]
  ..., 
  [136]
  [127]
  [134]]

 [[ 93]
  [102]
  [ 77]
  ..., 
  [141]
  [132]
  [133]]]
